### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zd3sf**
Moved the Flashing section and added more detail to ESPHome. General formatting

### CODE REVIEW

**Comment by mightymos** [comment]
The only conflict with the readme is that it seems microcontroller can output to uart/serial lines and interfere with ESP8285 during flashing of the ESP8285, like this user experienced:
https://github.com/mightymos/RF-Bridge-OB38S003/issues/12

But erasing the microcontroller can never be interfered with because it is the only device operating over I2C.

So the order in the readme should really have been erase microcontroller over I2C, flash ESP8285, then flash microcontroller.

Am I missing something there?

**Comment by mightymos** [comment]
> Okay I can try to make that clear. I did not know that the ESP8285 could interfere with the microcontroller as mine never did. I also flashed ESPHome on it once, and then updated the radio chip independently many times without touching the ESP.

Hmm okay, maybe we can get a definite answer soon.
Some other users were reporting problems.

It's explicitly a problem with the passthrough mode where the microcontroller is constantly manipulating the serial lines as GPIO to pass raw signal pulses. So that interferes with esptool or similar on the computer trying to talk to ESP8285. So actually on first flash starting from stock, you'd flash ESP8285 and then microcontroller. For any updates after that, the flash order would be reversed.

However, the other users seemed to be having trouble starting from stock firmware as well.
In that instance, I guess it would be random chance whether microcontroller is placing decoded radio data onto the serial lines or not.

So anyway, if in your experience, the readme is correct as is we can merge pull request.
Or if you can somehow communicate the nuance if I've explained it properly that would be helpful.
Just let me know either way.

**Comment by zd3sf** [comment]
Can I make other edits to the current pull request or do I need to edit my fork and submit a new request? Sorry this is my first contribution to github.

**Comment by mightymos** [comment]
I'm not sure, I'll just accept this one and you could make a new one.

**Pull request merged**
